// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmufolfdcblrluchwvjc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tdWZvbGZkY2Jscmx1Y2h3dmpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTgyMTksImV4cCI6MjA2NTQ5NDIxOX0.j-89SV17vvHLcADvF3QVXRz7ShYIMh3zgZNBXZAwQ3M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);